FUEL_LOST_PER_DISTANCE1: float = 5
FUEL_GAIN_PER_FUEL_CELL: int = 35
HEALTH_GAIN_PER_HEALTH_CELL: int = 40
TURN_COUNT: int = 0

# items earth
TOY_PRICE: float = 15.0
FUEL_CELL_PRICE: float = 40.0
FURNITURE: float = 75.0
PAINT_BUCKET: float = 30.0

TOY_WEIGHT: int = 2
FUEL_CELL_WEIGHT: int = 3
FURNITURE_WEIGHT: int = 10
PAINT_BUCKET_WEIGHT: int = 5

EARTH_MARKET: dict[str,float] = {
            "Toy": TOY_PRICE, 
            "Fuel cell": FUEL_CELL_PRICE, 
            "Furniture": FURNITURE, 
            "Paint bucket": PAINT_BUCKET
            }

EARTH_ITEM_WEIGHTS: list[int] = [TOY_WEIGHT,FUEL_CELL_WEIGHT,FURNITURE_WEIGHT,PAINT_BUCKET_WEIGHT]
EARTH_ITEM_PRICES_DEFAULT: list[float] = [TOY_PRICE,FUEL_CELL_PRICE,FURNITURE,PAINT_BUCKET]



# items kalsi
STEEL_PLATE_PRICE: float = 125.0
HEALTH_CELL_PRICE: float = 50.0
ROCKET_PART_PRICE: float = 200.0
IMMUNITY_HAZARD_PRICE: float = 75.0

STEEL_PLATE_WEIGHT: int = 25
HEALTH_CELL_WEIGHT: int = 3
ROCKET_PART_WEIGHT: int = 35
IMMUNITY_HAZARD_WEIGHT: int = 10

KALSI_MARKET: dict[str,float] = {
    "Steel plate": STEEL_PLATE_PRICE,
    "Health cell": HEALTH_CELL_PRICE,
    "Rocket part": ROCKET_PART_PRICE,
    "Hazard immunity": IMMUNITY_HAZARD_PRICE
}

KALSI_ITEM_WEIGHTS: list[int] = [STEEL_PLATE_WEIGHT,HEALTH_CELL_WEIGHT,ROCKET_PART_WEIGHT,IMMUNITY_HAZARD_WEIGHT]
KALSI_ITEM_PRICES_DEFAULT: list[float] = [STEEL_PLATE_PRICE,HEALTH_CELL_PRICE,ROCKET_PART_PRICE,IMMUNITY_HAZARD_PRICE]




# items Mars
MARKET_PREDICTOR_PRICE: float = 80.0
TELEPORT_PRICE: float = 85.0

MARKET_PREDICTOR_WEIGHT: int = 8
TELEPORT_WEIGHT: int = 15

MARS_MARKET: dict[str,float] = {
    "Market predictor": MARKET_PREDICTOR_PRICE,
    "Teleport device": TELEPORT_PRICE,
    "Health cell": HEALTH_CELL_PRICE,
    "Fuel cell": FUEL_CELL_PRICE
}

MARS_ITEM_WEIGHTS: list[int] = [MARKET_PREDICTOR_WEIGHT,TELEPORT_WEIGHT,HEALTH_CELL_WEIGHT,FUEL_CELL_WEIGHT]
MARS_ITEM_PRICE_DEFAULT: list[float] = [MARKET_PREDICTOR_PRICE,TELEPORT_PRICE,HEALTH_CELL_PRICE,FUEL_CELL_PRICE]







# venus items
MINNING_ASTEROID_DEVICE_PRICE: float = 100.0
EFFICIENCY_BOOSTER_PRICE: float = 60.0
GLASS_PRICE: float = 30.0

MINNING_ASTEROID_DEVICE_WEIGHT: int = 20
EFFICIENCY_BOOSTER_WEIGHT: int = 10
GLASS_WEIGHT: int = 5


VENUS_MARKET: dict[str,float] = {
    "Mining asteroid device": MINNING_ASTEROID_DEVICE_PRICE,
    "Efficiency booster": EFFICIENCY_BOOSTER_PRICE,
    "Glass": GLASS_PRICE,
    "Fuel cell": FUEL_CELL_PRICE
}

VENUS_ITEM_WEIGHTS: list[int] = [MINNING_ASTEROID_DEVICE_WEIGHT,EFFICIENCY_BOOSTER_WEIGHT,GLASS_WEIGHT,FUEL_CELL_WEIGHT]
VENUS_ITEM_PRICE_DEFAULT: list[float] = [MINNING_ASTEROID_DEVICE_PRICE,EFFICIENCY_BOOSTER_PRICE,GLASS_PRICE,FUEL_CELL_PRICE]
